### ISSUE TITLE
Release `kedro-datasets` 6.0.0

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-plugins#942]
### Description

Release kedro-datasets version `6.0.0`

### To-do

- [x] https://github.com/kedro-org/kedro-plugins/pull/898
- [x] https://github.com/kedro-org/kedro-plugins/pull/956 (Need to remove code that's marked as "to be removed": ibis dataset: https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/ibis/table_dataset.py#L123-L128)
- [x] https://github.com/kedro-org/kedro-plugins/pull/941
- [x] https://github.com/kedro-org/kedro-plugins/pull/909
- [ ] https://github.com/kedro-org/kedro-plugins/pull/938
- [x] https://github.com/kedro-org/kedro-plugins/pull/955
- [x] https://github.com/kedro-org/kedro-plugins/pull/961
